to_chinese = {
    "olive oil": "peanut oil",
    "burger": " chinese burger",
    "vegetable oil": "peanut oil",
    "canola oil": "peanut oil",
    "peanut oil": "peanut oil",
    "coconut oil": "peanut oil",
    "corn oil": "peanut oil",
    "sunflower oil": "peanut oil",
    "safflower oil": "peanut oil",
    "spaghetti pasta": "lo mein",
    "spaghetti": "lo mein",
    "vinegar": "black vinegar",
    "red pepper flakes": "dried chili pepper",
    "italian parsley": "cilantro",
    "parmigiano-reggiano cheese": "fermented bean curd",
    "penne": "lo mein",
    "mushrooms": "shiitake mushrooms",
    "salad": "malatang",
    "quesadilla": "xian bing",
    "Burger": "chinese hamburger",
    "french pancake": "jian bing",
    "meat sauce": "da lu mian",
    "churro": "you tiao",
    "pizza": "scallion pancake",
    "wine": "shaoxing wine",
    "chicken nuggets": "chicken balls",
    "jerky": "bak kwa",
    "pork": "mapo doufu",
    "meat": "bakkwa",
    "lamb": "lamb broth",
    "pasta": "lo mein",
    "sauce": "hoisin sauce",
    "shrimp": "cha jang mein",
    "tofu": "mapo tofu",
    "white rice": "jasmine scented rice",
    "corn": "bok choy",
    "ice cream": "baobing",
    "tea": "chinese tea",
    "sausage": "lap ceung",
    "salsa": "mala sauce",
    "maple sauce": "mala sauce",
    "maple syrup": "chinese mala syrup",
}

to_chinese_utensils = {
    "fork": "chopsticks",
    "frying pan": "wok",
    "pan": "wok",
    "rice cooker": "donabe",
    "cooker": "donabe",
    "spatula": "chuan",
    "ladle": "hoak",
    "pot": "wok",
    "steamers": "bamboo steamers",
}

to_healthy = {
    "vegetable oil": "olive oil",
    "potato": "zucchini",
    "canola oil": "olive oil",
    "olive oil": "olive oil",
    "peanut oil": "olive oil",
    "coconut oil": "olive oil",
    "corn oil": "olive oil",
    "sunflower oil": "olive oil",
    "safflower oil": "olive oil",
    "sesame oil": "olive oil",
    "coconut oil": "olive oil",
    "oil": "olive oil",
    "whole milk": "low-fat milk",
    "coconut milk": "almond milk",
    "soy milk": "almond milk",
    "almond milk": "almond milk",
    "ice cream": "low-fat frozen yoghurt",
    "whipping cream": "imitation whipped cream(made with skimmed milk)",
    "whipped cream": "imitation whipped cream(made with skimmed milk)",
    "sour cream": "plain low-fat yoghurt",
    "cream cheese": "fat-free cream cheese",
    "american cheese": "fat-free cheese",
    "cottage cheese": "low-fat cottage cheese",
    "mozzarella cheese": "part-skim milk mozzarella cheese",
    "ricotta cheese": "part-skim milk ricotta cheese",
    "granola": "oatmeal",
    "coffee cream": "low-fat milk",
    "ramen noodles": "rice",
    "almond flour": "almond flour",
    "flour": "almond flour",
    "bologna": "low-fat bologna",
    "sausage": "lean ham",
    "vegetable oil": "coconut oil",
    "tortillas": "lettuce leaves",
    "tortilla": "lettuce leaves",
    "couscous": "cauliflower rice",
    "rice": "cauliflower rice",
    "sugar": "stevia",
    "pasta sauce": "almond pesto",
    "penne": "whole wheat penne",
    "linguine": "whole wheat linguine",
    "fettuccine": "whole wheat fettuccine",
    "spaghetti": "spaghetti squash",
    "lasagna": "vegetable lasagna",
    "macaroni": "cauliflower",
    "mac and cheese": "cauliflower and cheese",
    "pasta salad": "mixed vegetables",
    "pasta": "veggie noodles",
    "breadcrumbs": "pork rinds",
    "bread crumbs": "pork rinds",
    "sliced bread": "eggplant",
    "white bread": "whole wheat bread",
    "pancakes": "oatmeal pancakes",
    "pizza crust": "fathead crust",
    "milk": "almond milk",
    "taco shell": "lettuce wrap",
    "french fries": "butternut squash fries",
    "hamburger buns": "portabello mushrooms",
    "burger buns": "portabello mushrooms",
    "buns": "portabello mushrooms",
    "scalloped potatoes": "tempeh",
    "mashed potatoes": "mashed cauliflower",
    "sweet potatoes": "zucchini",
    "potatoes": "zucchini",
    "potato chips": "kale chips",
    "hash browns": "squash",
    "bacon": "fresh pork belly",
    "baking soda": "sodium-free baking soda",
    "barbecue sauce": "low-sodium ketchup",
    "bbq sauce": "low-sodium ketchup",
    "beef jerky": "beef strips",
    "beef noodle soup": "mushroom broth",
    "blue cheese": "part-skim milk mozzarella cheese",
    "bullion": "mushroom broth",
    "camembert cheese": "part-skim milk mozzarella cheese",
    "canned anchovy": "low-sodium sardines",
    "canned corn": "fresh corn",
    "canned tomatoes": "fresh tomatoes",
    "capocollo": "low-sodium ham",
    "chicken noodle soup": "mushroom broth",
    "chicken soup": "mushroom broth",
    "cream of vegetable soup": "mushroom broth",
    "dried beef": "beef strips",
    "feta cheese": "part-skim milk mozzarella cheese",
    "fish sauce": "vinegar",
    "gouda cheese": "part-skim milk mozzarella cheese",
    "hot pepper sauce": "red pepper flakes",
    "instant soup": "mushroom broth",
    "italian salami": "low-sodium ham",
    "ketchup": "low-sodium ketchup",
    "marinade": "flavored vinegar",
    "mayonnaise": "yogurt",
    "mortadella": "low-sodium ham",
    "ground beef": "extra-lean ground beef",
    "olives": "baked grapes",
    "onion soup": "mushroom broth",
    "oyster sauce": "vinegar",
    "paremsan cheese": "part-skim milk mozzarella cheese",
    "pepperoni": "low-sodium ham",
    "pickle": "cucumber",
    "pickled eggplant": "eggplant",
    "pickled peppers": "fresh chiles",
    "prosciutto": "low-sodium ham",
    "queso seco": "part-skim milk mozzarella cheese",
    "ranch dressing": "balsamic vinegar",
    "relish": "low-sodium sweet relish",
    "romano cheese": "part-skim milk mozzarella cheese",
    "roquefort cheese": "part-skim milk mozzarella cheese",
    "salad dressing": "olive oil",
    "salami": "low-sodium ham",
    "salt and pepper": "pepper",
    "salt cod": "fresh cod",
    "salted butter": "unsalted butter",
    "salted mackerel": "fresh mackerel",
    "lightly salted": "",
    "salted": "",
    "sauerkraut": "chopped cabbage",
    "sea salt": "sesame oil",
    "salt": "low-sodium salt substitute",
    "smoked herring": "seared herring",
    "smoked salmon": "fresh salmon",
    "smoked white fish": "seared white fish",
    "soup cube": "mushroom broth",
    "soup": "vegetable puree",
    "soy sauce": "low-sodium soy sauce",
    "steak sauce": "low-sodium steak sauce",
    "stock cube": "mushroom broth",
    "stock": "mushroom broth",
    "table salt": "sesame oil",
    "teriyaki sauce": "vinegar",
    "tomato soup": "mushroom broth",
    "turkey bacon": "fresh turkey strips",
    "turkey salami": "low-sodium ham",
    "vegetable soup": "mushroom broth",
    "chocolate": "carob",
    "beef": "beef(trimmed of external fat)",
    "pork": "lean smoked ham",
    "breaded fish": "unbreaded shellfish",
    "fried fish": "unbreaded shellfish",
    "egg whites": "egg whites",
    "egg white": "egg white",
    "whole eggs": "egg whites",
    "eggs": "egg whites",
    "egg": "egg whites",
    "whole egg": "egg whites",
    "chorizo sausage": "turkey sausage",
    "croissants": "hard french rolls",
    "brioches": "hard french rolls",
    "butter": "whipped butter",
    "avocado": "cucumber slices",
    "margarine": "diet margarine",
    "cheddar cheese": "fat-free cheese",
    "cheese": "low-fat cheese",
    "chilli powder": "green chilli powder",
}

to_unhealthy = {
    "low-fat milk": "coffee cream",
    "low-fat frozen yoghurt": "ice cream",
    "yoghurt": "ice cream",
    "imitation whipped cream(made with skimmed milk)": "whipped cream",
    "skimmed milk": "high fat milk",
    "milk": "whole milk",
    "plain low-fat yoghurt": "sour cream",
    "fat-free cream cheese": "cream cheese",
    "fat-free cheese": "cheddar cheese",
    "low-fat cottage cheese": "cottage cheese",
    "part-skim milk mozzarella cheese": "roquefort cheese",
    "part-skim milk ricotta cheese": "ricotta cheese",
    "cheese": "cheddar cheese",
    "oatmeal": "granola",
    "rice": "white rice",
    "almond flour": "white flour",
    "flour": "white flour",
    "low-fat bologna": "high-fat bologna",
    "bologna": "high-fat bologna",
    "lean ham": "sausage",
    "coconut oil": "mustard oil",
    "olive oil": "mustard oil",
    "vegetable oil": "mustard oil",
    "canola oil": "mustard oil",
    "olive oil": "mustard oil",
    "peanut oil": "mustard oil",
    "coconut oil": "mustard oil",
    "corn oil": "mustard oil",
    "sunflower oil": "mustard oil",
    "safflower oil": "mustard oil",
    "sesame oil": "mustard oil",
    "coconut oil": "mustard oil",
    "oil": "mustard oil",
    "oil": "mustard oil",
    "lettuce leaves": "cheese tortilla",
    "cauliflower rice": "white rice",
    "stevia": "sugar",
    "almond pesto": "pasta sauce",
    "whole wheat penne": "penne",
    "whole wheat linguine": "linguine",
    "whole wheat fettuccine": "fettuccine",
    "spaghetti squash": "spaghetti",
    "vegetable lasagna": "lasagna",
    "cauliflower": "potatoes",
    "cauliflower and cheese": "mac and cheese",
    "mixed vegetables": "fried vegetables",
    "vegetables": "fried vegetables",
    "veggie noodles": "pasta",
    "pork rinds": "bread crumbs",
    "eggplant": "pickled eggplant",
    "whole wheat bread": "white bread",
    "wheat bread": "white bread",
    "bread": "white bread",
    "oatmeal pancakes": "pancakes",
    "fathead crust": "pizza crust",
    "almond milk": "whole milk",
    "lettuce wrap": "taco shell",
    "butternut squash fries": "french fries",
    "portabello mushrooms": "buns",
    "tempeh": "scalloped potatoes",
    "mashed cauliflower": "mashed potatoes",
    "zucchini": "potatoes",
    "kale chips": "potato chips",
    "squash": "hash browns",
    "fresh pork belly": "bacon",
    "sodium-free baking soda": "baking soda",
    "low-sodium ketchup": "ketchup",
    "beef strips": "dried beef",
    "mushroom broth": "vegetable soup",
    "low-sodium sardines": "canned anchovy",
    "fresh corn": "canned corn",
    "fresh tomatoes": "canned tomatoes",
    "tomatoes": "canned tomatoes",
    "low-sodium ham": "turkey salami",
    "vinegar": "teriyaki sauce",
    "red pepper flakes": "hot pepper sauce",
    "flavored vinegar": "marinade",
    "yogurt": "mayonnaise",
    "extra-lean ground beef": "ground beef",
    "baked grapes": "olives",
    "cucumber": "pickle",
    "fresh chiles": "pickled peppers",
    "balsamic vinegar": "ranch dressing",
    "low-sodium sweet relish": "relish",
    "pepper": "black pepper",
    "fresh cod": "salt cod",
    "unsalted butter": "salted butter",
    "fresh mackerel": "salted mackerel",
    "chopped cabbage": "sauerkraut",
    "sesame oil": "table salt",
    "low-sodium salt substitute": "salt",
    "salt": "high sodium salt",
    "seared herring": "fried herring",
    "fresh salmon": "fried salmon",
    "salmon": "fried salmon",
    "seared white fish": "fried white fish",
    "fish": "fried fish",
    "vegetable puree": "soup",
    "low-sodium soy sauce": "soy sauce",
    "low-sodium steak sauce": "steak sauce",
    "fresh turkey strips": "deli meat",
    "turkey strips": "deli meat",
    "turkey": "duck",
    "carob": "chocolate",
    "beef(trimmed of external fat)": "corned beef",
    "beef": "corned beef",
    "lean smoked ham": "bacon",
    "ham": "deli meat",
    "chicken": "duck",
    "unbreaded shellfish": "fried fish",
    "egg whites": "egg",
    "egg white": "egg",
    "turkey sausage": "chorizo sausage",
    "hard french rolls": "brioches",
    "whipped butter": "butter",
    "cucumber slices": "avocado",
    "diet margarine": "margarine",
    "low-fat cheese": "high-fat cheese",
    "sweet potatoes": "potatoes",
    "zucchini": "potatoes",
    "carrots": "glazed carrots",
    "carrot": "glazed carrot",
    "chilli powder": "red chilli powder",
    "lentils": "fried fish",
    "lentil": "fried fish",
}

to_vegan = {
    "chicken bouillon": "vegetable bouillon",
    "beef bouillon": "vegetable bouillon",
    "pork bouillon": "vegetable bouillon",
    "chicken broth": "vegetable broth",
    "beef broth": "vegetable broth",
    "chicken stock": "vegetable broth",
    "beef stock": "vegetable broth",
    "pork stock": "vegetable broth",
    "pepperoni": "tofurky deli slice",
    "pastrami": "tofurky deli slice",
    "salami": "tofurky deli slice",
    "ribs": "seitan ribs",
    "ground meat": "textured soy protein",
    "ground beef": "textured soy protein",
    "ground pork": "textured soy protein",
    "filet mignon": "portobello mushroom",
    "rib-eye": "portobello mushroom",
    "burger": "veggie burger",
    "meatball": "veggie meatball",
    "sausage": "veggie sausage",
    "chicken breast": "seitan tenders",
    "chicken thigh": "seitan tenders",
    "chicken leg": "seitan tenders",
    "chicken nuggets": "seitan nuggets",
    "chicken": "tofu",
    "pork": "tempeh",
    "jerky": "veggie jerky",
    "tuna": "tempeh",
    "tilapia": "tempeh",
    "sardine": "tempeh",
    "salmon": "tempeh",
    "squid": "tempeh",
    "cod": "tempeh",
    "clam": "tempeh",
    "halibut": "tempeh",
    "anchovy": "tempeh",
    "anchovie": "tempeh",
    "calamari": "tempeh",
    "shrimp": "tofu",
    "prawn": "tofu",
    "milk powder": "almond milk powder",
    "milk": "soy milk",
    "ice cream": "soy ice cream",
    "mozzarella cheese": "vegan mozzarella cheese",
    "mozzarella": "vegan mozzarella",
    "parmesan cheese": "vegan parmesan cheese",
    "cheese": "crumbled tofu",
    "butter": "vegan margarine",
    "yogurt": "almond milk yogurt",
    "scrambled egg": "tofu scramble",
    "egg whites": "tofu",
    "egg white": "tofu",
    "egg yolk": "tofu",
    "egg": "tofu",
    "yolk": "tofu",
    "instant pudding": "dairy free instant pudding",
    "pudding": "dairy free pudding",
    "sour cream": "vegan sour cream",
    "mayonnaise": "vegan mayonnaise",
    "ketchup": "vegan ketchup",
    "gelatin": "agar flakes",
    "honey": "agave nectar",
    "chocolate": "non-dairy chocolate",
    "hollandaise sauce": "vegan hollandaise sauce",
    "oyster sauce": "vegetarian oyster sauce",
    "worcestershire sauce": "organic worcestershire sauce",
    "bread": "wheat tortilla",
    "bread toasts": "wheat tortilla",
    "bagel": "vegan bagel",
    "pancake": "vegan pancake",
    "meat": "tofu",
    "beef": "tempeh",
    "veal": "tofu",
    "lamb": "tempeh",
    "bacon": "vegan bacon",
    "steak": "seitan steak",
    "turkey": "tofurky",
    "fish": "soy",
    "crab": "tofu",
    "ham": "veggie burger",
}

to_vegetarian = {
    "chicken bouillon": "vegetable bouillon",
    "beef bouillon": "vegetable bouillon",
    "pork bouillon": "vegetable bouillon",
    "chicken broth": "vegetable broth",
    "chicken stock": "vegetable broth",
    "beef stock": "vegetable broth",
    "beef broth": "vegetable broth",
    "pork stock": "vegetable broth",
    "clam juice": "vegetable broth",
    "fish juice": "vegetable broth",
    "oyster juice": "vegetable broth",
    "ground meat": "textured soy protein",
    "ground beef": "textured soy protein",
    "ground pork": "textured soy protein",
    "pepperoni": "veggie deli slice",
    "pastrami": "veggie deli slice",
    "salami": "veggie deli slice",
    "steak": "portobello mushroom",
    "filet mignon": "portobello mushroom",
    "rib-eye": "portobello mushroom",
    "ribs": "portobello mushroom",
    "burger": "veggie burger",
    "meatball": "veggie meatball",
    "sausage": "veggie sausage",
    "bacon": "veggie bacon",
    "turkey": "soy patties",
    "chicken breast": "seitan tenders",
    "chicken leg": "seitan tenders",
    "chicken thigh": "seitan tenders",
    "chicken nuggets": "soy nuggets",
    "chicken soup": "vegetable soup",
    "chicken": "tofu",
    "jerky": "veggie jerky",
    "pork": "tempeh",
    "meat": "tofurky deli slice",
    "beef": "tofurky deli slice",
    "veal": "tofurky deli slice",
    "lamb": "tofurky deli slice",
    "tuna": "tempeh",
    "tilapia": "tempeh",
    "sardine": "tempeh",
    "salmon": "tempeh",
    "squid": "tempeh",
    "cod": "tempeh",
    "clam": "tempeh",
    "halibut": "tempeh",
    "anchovy": "tempeh",
    "anchovie": "tempeh",
    "mackerel": "tempeh",
    "calamari": "tempeh",
    "shrimp": "tofu",
    "prawn": "tofu",
    "gelatin": "agar flakes",
    "fish": "soy",
    "crab": "tofu",
    "ham": "veggie burger",
}
